package telegram

import (
	"errors"
	"fmt"
	"html"
	"regexp"
	"strconv"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"github.com/jeremyakers/askdo/internal/proto"
)

// Callback action prefixes for approval-card buttons (design §9). The full
// callback_data is "<action>:<nonce>"; with a 128-bit hex nonce that is 34
// bytes, within the 64-byte Bot API cap.
const (
	ActionApprove = "a"
	ActionDeny    = "d"
	ActionDetails = "v"
)

// noncePattern is the 128-bit lowercase-hex approval nonce generated by the
// reviewer's notify stage (Wave 5 lane B). This package never generates
// nonces; it validates and embeds the caller-supplied one.
var noncePattern = regexp.MustCompile(`^[0-9a-f]{32}$`)

// continuationMarker splits an over-long field across adjacent parts.
const continuationMarker = "[continued]"

// partHeaderReserve leaves room for the "part i/n" header when chunking.
const partHeaderReserve = 96

// CardInput is the structured, already-redacted content of the required
// approval summary (design §9 "Required user experience").
//
// REDACTION CONTRACT: every string field must already be redacted by the
// caller — report fields come from a validated review whose instructions
// forbid secret values (plan §4.3). This package strips unsafe control
// characters, HTML-escapes all dynamic text, and never receives source
// bundles.
type CardInput struct {
	CapturedStdinBytes int64 // broker-verified metadata, never the script body
	// Host is the trusted target hostname (broker-supplied via bootstrap).
	Host string
	// Container is the trusted execution-environment description
	// (broker-supplied via bootstrap; empty when no container evidence
	// exists — the renderer then omits the Environment line). It carries
	// only what the broker itself observed; the renderer never guesses an
	// underlying host name.
	Container string
	// TargetUID is the execution identity of the dispatched process.
	TargetUID uint32
	// JobID is the ordinary job ID (request_id).
	JobID string
	// Operation is the exact shell-quoted command text, already constructed
	// by reviewer code from literal argv (display only; execution uses the
	// unquoted argv). It is never model output.
	Operation string
	// Reason is the requesting agent's stated purpose (not independently
	// verified operator intent).
	Reason string
	// Report is the validated frozen review report.
	Report proto.ReviewReport
	// Broker-observed credential masks, bound to the frozen manifest digest.
	WithheldRefs  []string
	WithheldCount int
	// ReviewerModel is the actual model that produced the review.
	ReviewerModel string
	// Expiry is the absolute approval expiry time.
	Expiry time.Time
	// SubmitterUID is the kernel peer UID of the requesting agent.
	SubmitterUID uint32
	// SubmitterName is the host-account lookup for SubmitterUID. The parent
	// guarantees current metadata in production; a directly constructed
	// CardInput with an empty name renders as "uid N".
	SubmitterName string
	// CWD is the working directory bound to the approved execution.
	CWD string
}

// DetailsInput extends CardInput with the fallback history for the Details
// renderer.
type DetailsInput struct {
	CardInput
	// ModelHistory is the ordered per-model outcome history.
	ModelHistory []proto.ModelHistoryEntry
}

// ApprovalOnlyInput contains operation facts and typed availability statuses,
// never a review report, model history text, or model identity.
type ApprovalOnlyInput struct {
	CapturedStdinBytes                                            int64
	Host, Container, JobID, Operation, Reason, SubmitterName, CWD string
	TargetUID, SubmitterUID                                       uint32
	Expiry                                                        time.Time
	Failures                                                      []proto.AvailabilityFailure
}

var safeProviderName = regexp.MustCompile(`^[a-zA-Z0-9_-]{1,128}$`)

func approvalOnlyBlocks(in ApprovalOnlyInput) ([]string, error) {
	if strings.TrimSpace(in.Host) == "" || strings.TrimSpace(in.JobID) == "" || len(in.JobID) > 64 || strings.TrimSpace(in.Operation) == "" || in.Expiry.IsZero() || len(in.Failures) > 16 {
		return nil, errors.New("telegram: incomplete approval-only request")
	}
	blocks := []string{}
	if len(in.Failures) > 0 {
		blocks = append(blocks, "<b>Provider status (typed, no provider error text)</b>\n")
	}
	for _, failure := range in.Failures {
		status := ""
		switch failure.Code {
		case proto.AvailabilityQuota:
			status = "rate limit or quota"
		case proto.AvailabilityTransport:
			status = "connection unavailable"
		case proto.AvailabilityTimeout:
			status = "provider timed out"
		case proto.AvailabilityInvalidConfig:
			status = "provider configuration unavailable"
		case proto.AvailabilityMalformedWire:
			status = "invalid provider response"
		case proto.AvailabilityCodexReLogin:
			status = "provider sign-in required"
		default:
			return nil, errors.New("telegram: invalid availability status")
		}
		name := failure.Name
		if !safeProviderName.MatchString(name) {
			name = "configured provider"
		}
		blocks = append(blocks, fmt.Sprintf("- <code>%s</code>: %s\n", esc(name), status))
	}
	blocks = append(blocks, fmt.Sprintf("<b>Host:</b> <code>%s</code>\n", esc(in.Host)))
	if env := stripControls(in.Container); env != "" {
		blocks = append(blocks, fmt.Sprintf("<b>Environment:</b> %s\n", esc(env)))
	}
	submitter := esc(in.SubmitterName)
	if submitter == "" {
		submitter = fmt.Sprintf("uid %d", in.SubmitterUID)
	}
	target := fmt.Sprintf("uid %d", in.TargetUID)
	if in.TargetUID == 0 {
		target = "root"
	}
	blocks = append(blocks, fmt.Sprintf("<b>Submitted by:</b> <code>%s</code> (uid %d) → %s\n", submitter, in.SubmitterUID, target))
	if in.CWD != "" {
		blocks = append(blocks, "<b>Working directory:</b>\n", fmt.Sprintf("<code>%s</code>\n", esc(displayPath(in.CWD))))
	}
	blocks = append(blocks, "\n<b>Command</b>\n", bashBlock(esc(in.Operation)), "\n\n<b>Reason (submitter-stated)</b>\n", esc(in.Reason)+"\n")
	if in.CapturedStdinBytes > 0 {
		blocks = append(blocks, fmt.Sprintf("<b>Input:</b> captured script input (%d bytes); review via bundle:stdin\n", in.CapturedStdinBytes))
	}
	blocks = append(blocks, fmt.Sprintf("\nExpires %s · job <code>%s</code>\n", esc(in.Expiry.UTC().Format(time.RFC3339)), esc(in.JobID)))
	return blocks, nil
}

// RenderApprovalOnlySummaryParts posts all unreviewed warnings before any
// potentially long command; every part precedes the actionable keyboard.
func RenderApprovalOnlySummaryParts(in ApprovalOnlyInput) ([]string, error) {
	blocks, err := approvalOnlyBlocks(in)
	if err != nil {
		return nil, err
	}
	why := "<b>Why no review:</b> administrator policy skipped AI review.\n"
	if len(in.Failures) > 0 {
		why = "<b>Why no review:</b> providers unavailable after fallback.\n"
	}
	warning := "<b>UNASSESSED:</b> No independent AI assessment took place. Consequences and risks, rollback, and dependency completeness were NOT assessed. Approving permits execution without an AI review.\n"
	static := "<b>NO AI REVIEW</b>\n" + why + warning
	parts, err := chunkBlocks(blocks, func(i, n int) string {
		return static + fmt.Sprintf("Job %s — unreviewed summary part %d/%d:\n\n", esc(in.JobID), i, n)
	})
	if err != nil {
		return nil, err
	}
	if len(parts) == 1 {
		parts[0] = static + parts[0]
	}
	return parts, nil
}

// RenderApprovalOnlyDetails is informational, with no report or decision controls.
func RenderApprovalOnlyDetails(in ApprovalOnlyInput) ([]string, error) {
	return RenderApprovalOnlySummaryParts(in)
}

// RenderApprovalOnlyCard reuses the fixed nonce-bound controls but does not
// imply that an expanded AI review exists behind Details.
func RenderApprovalOnlyCard(in ApprovalOnlyInput, nonce string) (string, InlineKeyboardMarkup, error) {
	_, kb, err := RenderCard(in.JobID, nonce)
	if err != nil {
		return "", kb, err
	}
	reason := "administrator policy"
	if len(in.Failures) > 0 {
		reason = "providers unavailable"
	}
	return fmt.Sprintf("<b>NO AI REVIEW</b> · %s. Consequences/risks, rollback and dependency completeness were NOT assessed. Job <code>%s</code> expires %s. Approve once executes exactly one time without AI review; Deny rejects; Details shows unreviewed facts only.", reason, esc(in.JobID), esc(in.Expiry.UTC().Format(time.RFC3339))), kb, nil
}

// RenderSummaryParts renders the complete required summary as an ordered
// sequence of HTML message texts. If the summary fits one message the
// result is a single unnumbered part; otherwise parts are numbered
// ("part i/n") and each is at most MaxMessageRunes AFTER entity parsing
// (counted as escaped length), targeting TargetChunkRunes. Chunk
// boundaries prefer section boundaries; each part carries complete,
// balanced tags — a section longer than one part splits its escaped body
// mid-section across re-opened continuation blocks. Warnings and
// uncertainties are never dropped. Every part must be sent before the
// approval card (SendApproval enforces the ordering and fails closed).
func RenderSummaryParts(in CardInput) ([]string, error) {
	if err := validateCardInput(in); err != nil {
		return nil, err
	}
	blocks := summaryBlocks(in)
	return chunkBlocks(blocks, func(i, n int) string {
		return fmt.Sprintf("Job %s — summary part %d/%d:\n\n", esc(in.JobID), i, n)
	})
}

// RenderCard builds the short approval-card text and the fixed
// [Approve once][Deny][Details] inline keyboard bound to nonce. The model
// never constructs these controls; nonce must be the 128-bit hex value
// generated by the reviewer notify stage.
func RenderCard(jobID, nonce string) (string, InlineKeyboardMarkup, error) {
	var kb InlineKeyboardMarkup
	jobID = stripControls(jobID)
	if jobID == "" || len(jobID) > 64 {
		return "", kb, errors.New("telegram: invalid job ID for approval card")
	}
	buttons := []struct {
		label  string
		action string
	}{
		{"Approve once", ActionApprove},
		{"Deny", ActionDeny},
		{"Details", ActionDetails},
	}
	row := make([]InlineKeyboardButton, 0, len(buttons))
	for _, b := range buttons {
		data, err := CallbackData(b.action, nonce)
		if err != nil {
			return "", kb, err
		}
		row = append(row, InlineKeyboardButton{Text: b.label, CallbackData: data})
	}
	kb.InlineKeyboard = [][]InlineKeyboardButton{row}
	text := fmt.Sprintf("Approval required for job %s (details above). Approve once executes exactly one time; Deny rejects the job; Details shows the expanded review.", esc(jobID))
	return text, kb, nil
}

// RenderReviewedCard adds the frozen review's security score to the short
// human-approval card. Approval remains a separate, nonce-bound human action.
func RenderReviewedCard(in CardInput, nonce string) (string, InlineKeyboardMarkup, error) {
	var kb InlineKeyboardMarkup
	if err := validateCardInput(in); err != nil {
		return "", kb, err
	}
	text, kb, err := RenderCard(in.JobID, nonce)
	if err != nil {
		return "", kb, err
	}
	return "Security risk: " + securityRiskScore(in.Report.Risk) + ". " + text, kb, nil
}

// RenderAutoNotice constructs a non-actionable policy notice from broker-frozen
// numeric facts. It never claims an operator approved the operation.
func RenderAutoNotice(jobID string, score int) (string, error) {
	if jobID == "" || len(jobID) > 64 || stripControls(jobID) != jobID || score < 1 || score > 4 {
		return "", errors.New("telegram: invalid auto-approval notice")
	}
	return fmt.Sprintf("<b>Auto-approval policy notice</b> · job <code>%s</code> · Security risk: %d/5. Policy selected auto-execution after notification and prelaunch checks. No human approval was requested or recorded.", esc(jobID), score), nil
}

func securityRiskScore(risk string) string {
	if risk == "unknown" {
		return "UNKNOWN"
	}
	return esc(risk) + "/5"
}

// CallbackData returns the "<action>:<nonce>" callback_data for a button,
// verifying the nonce shape and the 64-byte Bot API cap.
func CallbackData(action, nonce string) (string, error) {
	switch action {
	case ActionApprove, ActionDeny, ActionDetails:
	default:
		return "", fmt.Errorf("telegram: unknown callback action %q", action)
	}
	if !noncePattern.MatchString(nonce) {
		return "", errors.New("telegram: nonce must be 32 lowercase hex characters (128-bit)")
	}
	data := action + ":" + nonce
	if len(data) > MaxCallbackDataBytes {
		return "", fmt.Errorf("telegram: callback_data %d bytes exceeds %d", len(data), MaxCallbackDataBytes)
	}
	return data, nil
}

// RenderDetails renders the bounded expanded report (design §9 "Details"):
// effects, warnings with evidence references, missing context,
// reversibility and fallback history, as an ordered
// sequence of HTML message texts (chunked exactly like the summary). Details
// is informational only — it never grants or extends approval. The same
// redaction contract as CardInput applies.
func RenderDetails(in DetailsInput) ([]string, error) {
	if err := validateCardInput(in.CardInput); err != nil {
		return nil, err
	}
	var blocks []string
	add := func(format string, args ...any) { blocks = append(blocks, fmt.Sprintf(format, args...)) }

	add("<b>Details for job %s</b>\n", esc(in.JobID))
	add("<b>Security risk: %s</b>\n", securityRiskScore(in.Report.Risk))
	add("\n<b>Effects</b>\n")
	if len(in.Report.Effects) == 0 {
		add("- none reported\n")
	}
	for _, e := range in.Report.Effects {
		add("- %s\n", esc(e))
	}
	add("\n<b>Warnings (with evidence)</b>\n")
	if len(in.Report.Warnings) == 0 {
		add("- none reported\n")
	}
	for _, w := range in.Report.Warnings {
		add("- %s\n", esc(w.Message))
		add("  evidence: %s\n", esc(w.Evidence))
	}
	add("\n<b>Missing context / uncertainties</b>\n")
	if len(in.Report.MissingContext) == 0 {
		add("- none reported\n")
	}
	for _, m := range in.Report.MissingContext {
		add("- %s\n", esc(m))
	}
	add("\n<b>Reversibility:</b> ")
	add("%s\n", esc(in.Report.Reversibility))

	if in.WithheldCount > 0 {
		add("<b>Credential content withheld: %d</b>\n", in.WithheldCount)
		for _, ref := range in.WithheldRefs {
			add("- ")
			add("<code>%s</code>", esc(displayPath(ref)))
			add("\n")
		}
	}
	add("\n<b>Reviewer model history</b>\n")
	if len(in.ModelHistory) == 0 {
		add("- none recorded\n")
	}
	for _, h := range in.ModelHistory {
		line := fmt.Sprintf("- %s: %s", esc(h.Name), esc(h.Outcome))
		if h.Error != "" {
			line += fmt.Sprintf(" (%s)", esc(h.Error))
		}
		add("%s\n", line)
	}

	return chunkBlocks(blocks, func(i, n int) string {
		return fmt.Sprintf("Job %s — details part %d/%d:\n\n", esc(in.JobID), i, n)
	})
}

// validateCardInput enforces the minimal structural requirements for a
// renderable card. Content validation (bounds, enums) belongs to the
// reviewer's report validator; the renderer stays usable for any string.
func validateCardInput(in CardInput) error {
	switch {
	case strings.TrimSpace(in.Host) == "":
		return errors.New("telegram: card requires a host")
	case strings.TrimSpace(in.JobID) == "" || len(in.JobID) > 64:
		return errors.New("telegram: card requires a job ID")
	case strings.TrimSpace(in.Operation) == "":
		return errors.New("telegram: card requires an operation description")
	case strings.TrimSpace(in.Report.Risk) == "":
		return errors.New("telegram: card requires a risk assessment")
	case strings.TrimSpace(in.ReviewerModel) == "":
		return errors.New("telegram: card requires the reviewer model name")
	case in.Expiry.IsZero():
		return errors.New("telegram: card requires an expiry time")
	}
	if in.WithheldCount < 0 || in.WithheldCount > 1000000 || len(in.WithheldRefs) > 16 || len(in.WithheldRefs) > in.WithheldCount {
		return errors.New("telegram: invalid withheld facts")
	}
	for _, ref := range in.WithheldRefs {
		if ref == "" || len(ref) > 1024 || strings.ContainsRune(ref, 0) {
			return errors.New("telegram: invalid withheld reference")
		}
	}
	return nil
}

// summaryBlocks builds the required summary content as HTML section blocks
// so chunking can prefer section boundaries. Every required design §9
// element is present: heading with host/environment/risk, submitter,
// working directory, command, reason, review summary, effects, ALL
// warnings, uncertainties, reversibility, reviewer model, expiry
// and job ID. All dynamic text is escaped before wrapping.
func summaryBlocks(in CardInput) []string {
	var blocks []string
	add := func(format string, args ...any) { blocks = append(blocks, fmt.Sprintf(format, args...)) }

	add("<b>Privilege approval · Security risk: %s</b>\n", securityRiskScore(in.Report.Risk))
	// Withheld credentials are an operator decision, never a reviewer one:
	// the warning leads the summary (always before Approve/Deny, never only
	// behind Details) with the count and every withheld reference. Refs are
	// proto-bounded (validated in validateCardInput) and escaped/quoted here.
	if in.WithheldCount > 0 {
		add("<b>Credential content withheld from AI review: %d</b>\n", in.WithheldCount)
		for _, ref := range in.WithheldRefs {
			add("- ")
			add("<code>%s</code>", esc(displayPath(ref)))
			add("\n")
		}
	}
	add("<b>Host:</b> <code>%s</code>\n", esc(in.Host))
	if env := stripControls(in.Container); env != "" {
		add("<b>Environment:</b> %s\n", esc(env))
	}

	submitter := esc(in.SubmitterName)
	if submitter == "" {
		submitter = fmt.Sprintf("uid %d", in.SubmitterUID)
	}
	target := fmt.Sprintf("uid %d", in.TargetUID)
	if in.TargetUID == 0 {
		target = "root"
	}
	add("<b>Submitted by:</b> <code>%s</code> (uid %d) → %s\n", submitter, in.SubmitterUID, target)
	if in.CWD != "" {
		add("<b>Working directory:</b>\n")
		add("<code>%s</code>", esc(displayPath(in.CWD)))
		add("\n")
	}

	// The exact command, shell-quoted for display only, in a Bash block.
	// Continuation chunking keeps the full command; nothing is ellipsized.
	add("\n<b>Command</b>\n")
	add("%s", bashBlock(esc(in.Operation)))
	if in.CapturedStdinBytes > 0 {
		add("\n<b>Input:</b> captured script input (%d bytes); review via bundle:stdin", in.CapturedStdinBytes)
	}

	add("\n\n<b>Reason</b>\n")
	add("%s\n", esc(in.Reason))
	if s := stripControls(in.Report.Summary); s != "" {
		add("\n<b>Review summary</b>\n")
		add("%s\n", esc(s))
	}

	if len(in.Report.Effects) == 0 {
		add("\n<b>Effects</b>\n- none reported\n")
	} else {
		add("\n<b>Effects</b>\n")
		for _, e := range in.Report.Effects {
			add("- %s\n", esc(e))
		}
	}

	// All material warnings, always on the card path, never behind Details.
	if len(in.Report.Warnings) == 0 {
		add("\n<b>Warnings</b>\n- none reported\n")
	} else {
		add("\n<b>Warnings</b>\n")
		for _, w := range in.Report.Warnings {
			add("• %s\n", esc(w.Message))
		}
	}

	if len(in.Report.MissingContext) == 0 {
		add("\n<b>Uncertainties</b>\n- none reported\n")
	} else {
		add("\n<b>Uncertainties</b>\n")
		for _, m := range in.Report.MissingContext {
			add("• %s\n", esc(m))
		}
	}

	add("\n<b>Reversibility:</b> ")
	add("%s\n", esc(in.Report.Reversibility))
	add("\nReviewer <code>%s</code> · expires %s · job <code>%s</code>\n",
		esc(in.ReviewerModel), esc(in.Expiry.UTC().Format(time.RFC3339)), esc(in.JobID))
	return blocks
}

// bashBlock wraps already-escaped command text in a preformatted Bash code
// block.
func bashBlock(escaped string) string {
	return "<pre><code class=\"language-bash\">" + escaped + "</code></pre>"
}

// displayPath keeps ordinary paths readable, but quotes a path containing
// nonprinting characters so no directory or reference appears to be a
// different one after rendering. Quoting also distinguishes real controls
// from literal backslash escape sequences; HTML escaping happens afterward.
func displayPath(path string) string {
	if utf8.ValidString(path) && strings.IndexFunc(path, func(r rune) bool { return !unicode.IsPrint(r) }) < 0 {
		return path
	}
	return strconv.Quote(path)
}

// chunkBlocks packs HTML blocks into an ordered sequence of message texts.
// A single fitting message is returned unnumbered; multiple parts get a
// numbered header. Part sizes are measured AFTER entity expansion (the
// Telegram limit applies to the parsed text), targeting TargetChunkRunes
// with a hard MaxMessageRunes cap. A section block longer than one part
// splits its escaped body mid-section across parts, each carrying the
// complete enclosing tags and continuation markers — content is never
// dropped. The result is guaranteed ≤ MaxMessageRunes per part or an error
// (fail closed — never emit an oversized message).
//
// Every block must be well-formed on its own: each <pre>/<code> wrapper is
// re-opened on each part, never left spanning a boundary mid-tag.
func chunkBlocks(blocks []string, header func(i, n int) string) ([]string, error) {
	// Measure against the Telegram limit: entity expansion means the
	// escaped text is what the server parses, so use its rune count.
	total := 0
	for _, b := range blocks {
		total += utf8.RuneCountInString(b)
	}
	if total <= TargetChunkRunes {
		return []string{strings.Join(blocks, "")}, nil
	}

	budget := TargetChunkRunes - partHeaderReserve
	var parts []string
	var cur strings.Builder
	curLen := 0
	flush := func() {
		if curLen > 0 {
			parts = append(parts, cur.String())
			cur.Reset()
			curLen = 0
		}
	}
	for _, block := range blocks {
		for {
			blockLen := utf8.RuneCountInString(block)
			if curLen > 0 && curLen+blockLen > budget {
				flush()
				continue
			}
			if blockLen <= budget-curLen {
				cur.WriteString(block)
				curLen += blockLen
				break
			}
			// Fresh part (curLen == 0) and the block still exceeds the
			// budget: split the block's escaped text at a rune boundary,
			// re-opening the block's wrapping tags on each side so every
			// part stays well-formed. The block may itself be a
			// continuation fragment (leading marker) of an oversized
			// section from a previous iteration.
			room := budget - utf8.RuneCountInString(continuationMarker) - 2
			if room < 1 {
				return nil, errors.New("telegram: cannot chunk summary within message cap")
			}
			prefix, open, body, close := unwrapTags(block)
			runes := []rune(body)
			if len(runes) <= room {
				// Only the wrapper overhead exceeded the budget; emit whole.
				cur.WriteString(block)
				curLen += blockLen
				break
			}
			// Never split inside a character reference: back up to the
			// last complete entity within the fragment.
			cut := room
			for cut > 0 && incompleteEntityAt(string(runes[:cut])) {
				cut--
			}
			first := prefix + open + string(runes[:cut]) + close
			cur.WriteString(first)
			cur.WriteString("\n" + continuationMarker + "\n")
			curLen += utf8.RuneCountInString(first) + 2 + utf8.RuneCountInString(continuationMarker)
			flush()
			// The consumed prefix belongs to this fragment only. Repeating it
			// would hide the wrapper from unwrapTags on the next split.
			block = continuationMarker + "\n" + open + string(runes[cut:]) + close
		}
	}
	flush()

	n := len(parts)
	out := make([]string, n)
	for i, p := range parts {
		out[i] = header(i+1, n) + p
		if utf8.RuneCountInString(out[i]) > MaxMessageRunes {
			return nil, fmt.Errorf("telegram: part %d/%d exceeds the %d-rune message cap", i+1, n, MaxMessageRunes)
		}
	}
	return out, nil
}

// unwrapTags strips one balanced wrapper tag pair (<pre><code …>…</code>
// </pre> or <code>…</code>) from a block. Text without a wrapper is
// returned unchanged. Only the fixed wrapper shapes this package emits are
// recognized. A continuation block (leading "[continued]\n" marker) keeps
// its marker as prefix so repeated splits re-open the same wrapper.
func unwrapTags(block string) (prefix, open, body, close string) {
	rest := block
	var pre string
	if strings.HasPrefix(rest, continuationMarker+"\n") {
		pre = continuationMarker + "\n"
		rest = rest[len(pre):]
	}
	for _, pair := range [...][2]string{
		{"<pre><code class=\"language-bash\">", "</code></pre>"},
		{"<code>", "</code>"},
	} {
		if strings.HasPrefix(rest, pair[0]) && strings.HasSuffix(rest, pair[1]) {
			return pre, pair[0], rest[len(pair[0]) : len(rest)-len(pair[1])], pair[1]
		}
	}
	return "", "", rest, ""
}

// incompleteEntityAt reports whether the tail of s contains an ampersand
// that has not yet been closed by a semicolon, i.e. a character reference
// would be split by appending more text at this point.
func incompleteEntityAt(s string) bool {
	amp := strings.LastIndexByte(s, '&')
	if amp < 0 {
		return false
	}
	return !strings.ContainsRune(s[amp:], ';')
}

// esc strips unsafe control characters and HTML-escapes the result so no
// dynamic text can introduce tags, links, fake headings or delimiters.
func esc(s string) string {
	return html.EscapeString(stripControls(s))
}

// stripControls removes unsafe control characters from rendered text:
// newline is kept; all other C0 controls, DEL, the C1 range, bidi
// overrides/embeddings, and zero-width/format controls are dropped.
func stripControls(s string) string {
	return strings.Map(func(r rune) rune {
		switch {
		case r == '\n':
			return r
		case r < 0x20 || (r >= 0x7F && r <= 0x9F):
			return -1
		case r >= 0x200B && r <= 0x200F: // zero-width space/non-joiner/joiner, LRM, RLM
			return -1
		case r >= 0x202A && r <= 0x202E: // bidi embeddings/overrides
			return -1
		case r >= 0x2060 && r <= 0x2064: // word joiner, invisible operators
			return -1
		case r >= 0x2066 && r <= 0x206F: // bidi isolates, deprecated format
			return -1
		case r == 0xFEFF: // BOM / zero-width no-break space
			return -1
		}
		return r
	}, s)
}
